### ISSUE TITLE
order_by('?') is very inefficient

### ISSUE THREAD

**Issue by simonw** [philippWassibauer/django-activity-stream#1]
The get_people_i_follow() and get_my_followers() functions both use order_by('?') - this is an extremely inefficient database operation. It looks like this is being done to emphasize the non-ordered nature of the data, in which case I would recommend calling Python's set() function on the queryset instead.

**Comment by philippWassibauer** [comment]
thanks for pointing it out, I actually did not know about the set() command.  i changed it to the default ordering of the objects now and added an offset parameter as well.
